# Generated by Django 4.2.1 on 2023-05-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.cources')),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('instruction', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('points', models.CharField(default='No points', max_length=5)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_checked', models.BooleanField()),
                ('is_missed', models.BooleanField()),
                ('is_done', models.BooleanField()),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.cources')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.themes')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
