# Generated by Django 4.2.1 on 2023-05-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_rename_courcefeed_courcestream'),
        ('tasks', '0002_alter_tasks_is_checked_alter_tasks_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cources.cources'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.themes'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='cources.cources'),
        ),
    ]
