# Generated by Django 4.2.1 on 2023-05-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_alter_courcestream_options_courcestream_date_and_more'),
        ('tasks', '0003_alter_tasks_cource_alter_tasks_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='tasks.themes'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='cources.cources'),
        ),
    ]
