# Generated by Django 4.2.1 on 2023-05-21 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0013_remove_streamcomments_tream_streamcomments_stream_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_tasks_theme_alter_themes_cource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tasks.tasks'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='tasks.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='cources.cources'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='tasks.themes'),
        ),
    ]
