# Generated by Django 4.2.1 on 2023-06-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_rename_upload_file_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
    ]
