# Generated by Django 4.2.1 on 2023-05-16 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('subject', models.CharField(max_length=155)),
                ('is_archived', models.BooleanField()),
                ('students', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cources',
            },
        ),
    ]
