# Generated by Django 4.2.1 on 2023-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_alter_cources_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='code',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
