# Generated by Django 4.2.1 on 2023-05-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cources', '0006_rename_courcefeed_courcestream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courcestream',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='courcestream',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='courcestream',
            name='is_group_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cources',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courcestream',
            name='cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='cources.cources'),
        ),
        migrations.CreateModel(
            name='StreamComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('tream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.courcestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
