# Generated by Django 4.2.1 on 2023-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_alter_courcestream_options_courcestream_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courcestream',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
