# Generated by Django 4.2.1 on 2023-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_alter_courcestream_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courcestream',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
