# Generated by Django 4.2.1 on 2023-05-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0010_courcestream_is_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courcestream',
            old_name='message',
            new_name='text',
        ),
    ]
