# Generated by Django 4.2.1 on 2023-05-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0011_rename_message_courcestream_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courcestream',
            name='is_theme',
        ),
    ]
