# Generated by Django 4.2.1 on 2023-05-21 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cources', '0012_remove_courcestream_is_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamcomments',
            name='tream',
        ),
        migrations.AddField(
            model_name='streamcomments',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cources.courcestream'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
