# Generated by Django 4.2.1 on 2023-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0015_courcestream_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
