# Generated by Django 4.2.1 on 2023-06-13 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cources', '0017_privateroom_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
